#!/usr/bin/env bash
#
# test_woz_batch.sh — bulk-test WOZ disk images, resumable, with HTML report
#
# Usage:
#   ./test_woz_batch.sh [--out DIR] [--frames N] [--timeout S] [--batch N]
#                       [--retest FILE] [--redo-status STATUS]
#
# Modes (one of):
#   default     Process every .woz under woztest/ not already in results.csv.
#               Safe to re-run after Ctrl-C; resumes where it left off.
#   --batch N   Process at most N new disks this invocation, then exit.
#               Good for doing the full set in chunks.
#   --retest FILE
#               Re-run only the paths listed in FILE (one .woz per line).
#               Existing rows are replaced. Use the "Download retest list"
#               button in the HTML to generate such a file.
#   --redo-status STATUS
#               Re-run every disk whose current status is STATUS. Handy for
#               retrying TIMEOUT / CRASH / BLANK after a sim fix, e.g.
#               --redo-status TIMEOUT.
#
# Options:
#   --out DIR       Output directory (default: woz_report). Reused between runs
#                   for resume, so point at the same directory to continue.
#   --frames N      Frames per test (default 1000)
#   --timeout S     Per-disk wall-clock timeout seconds (default 300)
#   --jobs N, -j N  Run N disks in parallel (default 1). With 7+ cores, -j 7
#                   finishes the full set in ~1/7 the wall-clock time. Each
#                   worker writes its own screenshot via --screenshot-name so
#                   workers don't collide in the same cwd.
#
# Files produced in DIR/:
#   index.html            human-review page
#   results.csv           one row per disk, authoritative state
#   shots/<hash>.png      deduped screenshot images
#   retest.txt            generated by HTML checkboxes when you download

set -uo pipefail

FRAMES=1000
TIMEOUT=300
BATCH=0
JOBS=1
RETEST=""
REDO_STATUS=""
OUT="woz_report"
WOZTEST_DIR="woztest"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --frames)       FRAMES="$2"; shift 2 ;;
    --timeout)      TIMEOUT="$2"; shift 2 ;;
    --batch)        BATCH="$2"; shift 2 ;;
    --jobs|-j)      JOBS="$2"; shift 2 ;;
    --retest)       RETEST="$2"; shift 2 ;;
    --redo-status)  REDO_STATUS="$2"; shift 2 ;;
    --out)          OUT="$2"; shift 2 ;;
    --help|-h)
      sed -n '3,42p' "$0"; exit 0 ;;
    *) echo "Unknown argument: $1" >&2; exit 2 ;;
  esac
done

if [[ ! -x ./obj_dir/Vemu ]]; then
  echo "ERROR: ./obj_dir/Vemu not found — run make first" >&2
  exit 1
fi
if [[ ! -d "$WOZTEST_DIR" ]]; then
  echo "ERROR: $WOZTEST_DIR/ not found" >&2
  exit 1
fi

mkdir -p "$OUT/shots"
CSV="$OUT/results.csv"
HTML="$OUT/index.html"

# CSV header if new
if [[ ! -f "$CSV" ]]; then
  echo "status,png_size,png_hash,seconds,rc,woz_path" > "$CSV"
fi

# Enumerate all .woz. For games that ship as multi-disk sets, only test
# "disk 1" (or the sole disk) so we don't waste time trying to boot
# disk 2/3/4/etc. Heuristic:
#   - If a filename contains "disk N" (any case), keep only N=1
#   - Or "side A/B": keep side A
#   - Or "- Disk 1 -" / "- Side A -" style
#   - Keep files that don't match these patterns (single-disk games)
# Raw enumeration is kept in ALL_WOZ_RAW for the total count; the filtered
# set goes to ALL_WOZ and drives actual work selection.
ALL_WOZ_RAW=$(mktemp)
ALL_WOZ=$(mktemp)
find "$WOZTEST_DIR" -name '*.woz' -type f | sort > "$ALL_WOZ_RAW"
awk '
  {
    # Match on lowercased basename so patterns work regardless of case
    n = split($0, parts, "/")
    fname = tolower(parts[n])
    # If filename mentions "disk N", keep only disk 1* variants
    if (match(fname, / disk *[0-9]+/)) {
      if (match(fname, / disk *1[^0-9]/) || match(fname, / disk *1$/)) print $0
      next
    }
    # If filename mentions "side X", keep only side A variants
    if (match(fname, / side *[a-z]/)) {
      if (match(fname, / side *a[^a-z]/) || match(fname, / side *a$/)) print $0
      next
    }
    # No disk/side marker: single-disk image — keep
    print $0
  }
' "$ALL_WOZ_RAW" > "$ALL_WOZ"
TOTAL_RAW=$(wc -l < "$ALL_WOZ_RAW" | tr -d ' ')
TOTAL=$(wc -l < "$ALL_WOZ" | tr -d ' ')
echo "Found $TOTAL_RAW .woz files; testing $TOTAL first-disk/side-A images (skipping additional disks)"

# Build working set based on mode
WORK_LIST=$(mktemp)
DONE_LIST=$(mktemp)
# Extract already-processed paths from CSV column 6 (may be quoted)
awk -F',' 'NR>1 {
  p = $6
  gsub(/^"/,"",p); gsub(/"$/,"",p)
  print p
}' "$CSV" > "$DONE_LIST"

if [[ -n "$RETEST" ]]; then
  if [[ ! -f "$RETEST" ]]; then
    echo "ERROR: retest file not found: $RETEST" >&2
    exit 1
  fi
  # Process everything in the retest file; remove those from CSV so we rerun them
  grep -v '^[[:space:]]*$' "$RETEST" > "$WORK_LIST"
  # Remove matching rows from CSV
  awk -F',' -v retest="$RETEST" '
    BEGIN {
      while ((getline line < retest) > 0) if (line != "") skip[line] = 1
    }
    NR == 1 { print; next }
    {
      p = $6
      gsub(/^"/,"",p); gsub(/"$/,"",p)
      if (!(p in skip)) print
    }
  ' "$CSV" > "$CSV.new"
  mv "$CSV.new" "$CSV"
  echo "Retest mode: $(wc -l < "$WORK_LIST" | tr -d ' ') disks"
elif [[ -n "$REDO_STATUS" ]]; then
  # Pull paths with the given status; remove their rows
  awk -F',' -v s="$REDO_STATUS" '
    NR > 1 && $1 == s {
      p = $6; gsub(/^"/,"",p); gsub(/"$/,"",p); print p
    }
  ' "$CSV" > "$WORK_LIST"
  awk -F',' -v s="$REDO_STATUS" 'NR == 1 || $1 != s' "$CSV" > "$CSV.new"
  mv "$CSV.new" "$CSV"
  echo "Redo-status $REDO_STATUS: $(wc -l < "$WORK_LIST" | tr -d ' ') disks"
else
  # Default: all .woz not already in CSV
  grep -F -x -v -f "$DONE_LIST" "$ALL_WOZ" > "$WORK_LIST" || true
  REMAINING=$(wc -l < "$WORK_LIST" | tr -d ' ')
  DONE_COUNT=$(wc -l < "$DONE_LIST" | tr -d ' ')
  echo "Progress: $DONE_COUNT of $TOTAL processed; $REMAINING remaining"
fi

if [[ "$BATCH" -gt 0 ]]; then
  head -n "$BATCH" "$WORK_LIST" > "$WORK_LIST.batch"
  mv "$WORK_LIST.batch" "$WORK_LIST"
  echo "Batch size: processing $(wc -l < "$WORK_LIST" | tr -d ' ') disks this run"
fi

WORK_COUNT=$(wc -l < "$WORK_LIST" | tr -d ' ')
if [[ "$WORK_COUNT" -eq 0 ]]; then
  echo "Nothing to do."
  # Still rebuild HTML from current CSV
else
  echo "Output directory: $OUT"
  echo "Frames: $FRAMES, timeout: ${TIMEOUT}s"
  echo ""
fi

rm -f screenshot_frame_*.png

# ---------- Run tests ----------
# Shared state for workers (exported so subshells can see them)
TMPDIR_WORK=$(mktemp -d -t woz_batch_XXXXXX)
trap 'rm -rf "$TMPDIR_WORK"' EXIT
PROGRESS_FILE="$TMPDIR_WORK/progress"
echo 0 > "$PROGRESS_FILE"

export OUT CSV FRAMES TIMEOUT WORK_COUNT TMPDIR_WORK PROGRESS_FILE

# Worker: process one disk. Called with the woz path as $1.
# Writes a CSV row via flock and prints a progress line.
run_one_disk() {
  local woz="$1"
  [[ -z "$woz" ]] && return 0

  # Unique per-invocation screenshot path so parallel workers don't collide
  local shot="$TMPDIR_WORK/shot.$$.$RANDOM.png"

  local start end elapsed rc png_size hash status
  start=$(date +%s)
  if command -v gtimeout >/dev/null 2>&1; then
    gtimeout "$TIMEOUT" ./obj_dir/Vemu --quiet --no-cpu-log \
        --woz "$woz" --stop-at-frame "$FRAMES" --screenshot "$FRAMES" \
        --screenshot-name "$shot" \
        >/dev/null 2>&1
    rc=$?
  else
    ./obj_dir/Vemu --quiet --no-cpu-log \
        --woz "$woz" --stop-at-frame "$FRAMES" --screenshot "$FRAMES" \
        --screenshot-name "$shot" \
        >/dev/null 2>&1 &
    local pid=$!
    (sleep "$TIMEOUT" && kill -9 "$pid" 2>/dev/null) & local watchdog=$!
    wait "$pid" 2>/dev/null
    rc=$?
    kill "$watchdog" 2>/dev/null
  fi
  end=$(date +%s)
  elapsed=$((end - start))

  if [[ -f "$shot" ]]; then
    png_size=$(stat -f%z "$shot" 2>/dev/null || stat -c%s "$shot")
    hash=$(md5 -q "$shot" 2>/dev/null || md5sum "$shot" | awk '{print $1}')
    if [[ "$rc" -eq 124 || "$rc" -eq 137 ]]; then
      status=TIMEOUT
    elif [[ "$png_size" -lt 5600 ]]; then
      status=BLANK
    elif [[ "$png_size" -lt 6500 ]]; then
      status=TEXT_ONLY
    else
      status=BOOTED
    fi
  else
    png_size=0
    hash=""
    status=CRASH
  fi

  # Serialize writes: dedupe screenshot, append CSV row, bump progress counter.
  # Use mkdir as an atomic lock (portable across macOS / Linux, no flock needed).
  local lockdir="$TMPDIR_WORK/lock"
  while ! mkdir "$lockdir" 2>/dev/null; do sleep 0.05; done
  if [[ -n "$hash" && ! -f "$OUT/shots/$hash.png" ]]; then
    cp "$shot" "$OUT/shots/$hash.png"
  fi
  printf '%s,%d,%s,%d,%d,"%s"\n' "$status" "$png_size" "$hash" "$elapsed" "$rc" "$woz" >> "$CSV"
  local n=$(( $(< "$PROGRESS_FILE") + 1 ))
  echo "$n" > "$PROGRESS_FILE"
  printf '[%4d/%4d] %-10s %6d bytes  %3ds  %s\n' \
      "$n" "$WORK_COUNT" "$status" "$png_size" "$elapsed" "$woz"
  rmdir "$lockdir"

  rm -f "$shot"
}
export -f run_one_disk

if [[ "$JOBS" -le 1 ]]; then
  # Sequential mode
  while IFS= read -r woz; do
    [[ -z "$woz" ]] && continue
    run_one_disk "$woz"
  done < "$WORK_LIST"
else
  # Parallel mode. Use NUL separators so paths with spaces survive xargs.
  # macOS's xargs lacks -d, but -0 works everywhere.
  echo "Parallelism: $JOBS workers"
  tr '\n' '\0' < "$WORK_LIST" | \
    xargs -0 -n1 -P "$JOBS" -I {} bash -c 'run_one_disk "$@"' _ {}
fi

rm -f screenshot_frame_*.png

# ---------- Build HTML report ----------
TESTED=$(awk 'NR>1' "$CSV" | wc -l | tr -d ' ')
cat > "$HTML" <<HTML_HEAD
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>WOZ Boot Report</title>
<style>
  body { font-family: -apple-system, sans-serif; margin: 20px; background: #f4f4f4; }
  h1 { margin: 0 0 6px 0; }
  .meta { color: #666; margin-bottom: 15px; }
  .summary-bar { display: flex; gap: 20px; padding: 10px 15px; background: #fff;
                 border: 1px solid #ccc; border-radius: 4px; margin-bottom: 15px; }
  .filters { margin: 15px 0; }
  .filters button { padding: 6px 12px; margin-right: 6px; border: 1px solid #888;
                    background: #fff; cursor: pointer; border-radius: 4px; }
  .filters button.active { background: #2a6; color: #fff; border-color: #2a6; }
  .retest-bar { margin: 15px 0; padding: 10px; background: #fff8cc;
                border: 1px solid #c90; border-radius: 4px; display: none; }
  .retest-bar.active { display: block; }
  .retest-bar a { color: #06c; font-weight: bold; }
  .group { background: #fff; border: 1px solid #ccc; border-radius: 6px;
           margin-bottom: 12px; padding: 10px; }
  .group-header { display: flex; align-items: center; gap: 15px; }
  .group-header img {
    width: 400px;
    border: 1px solid #888;
    image-rendering: pixelated;
    cursor: zoom-in;
    transition: transform 0.15s;
  }
  .group-header img:hover {
    transform: scale(1.02);
    box-shadow: 0 4px 12px rgba(0,0,0,0.3);
  }
  /* Full-size lightbox overlay when an image is clicked */
  #lightbox {
    display: none;
    position: fixed; inset: 0;
    background: rgba(0,0,0,0.9);
    z-index: 1000;
    align-items: center; justify-content: center;
    cursor: zoom-out;
  }
  #lightbox.open { display: flex; }
  #lightbox img {
    max-width: 95vw; max-height: 95vh;
    image-rendering: pixelated;
    border: 1px solid #444;
  }
  .group-info { flex: 1; }
  .status { display: inline-block; padding: 2px 8px; border-radius: 3px;
            font-weight: bold; font-size: 12px; color: #fff; }
  .status.BOOTED    { background: #2a6; }
  .status.TEXT_ONLY { background: #ca3; }
  .status.BLANK     { background: #888; }
  .status.TIMEOUT   { background: #c33; }
  .status.CRASH     { background: #808; }
  .count { color: #555; font-size: 14px; }
  details { margin-top: 8px; }
  summary { cursor: pointer; color: #06c; font-size: 13px; }
  .disks { margin-top: 8px; padding-left: 20px; }
  .disks > div { font-family: monospace; font-size: 12px; padding: 2px 0;
                 display: flex; align-items: center; gap: 6px; }
  .disks .cmd { color: #888; font-size: 11px; margin-left: 6px; }
  .mark-group { margin-left: auto; font-size: 12px; }
</style>
</head>
<body>
<h1>WOZ Boot Report</h1>
<div class="meta">
  Updated $(date) &nbsp;&nbsp; Frames: $FRAMES &nbsp;&nbsp; Timeout: ${TIMEOUT}s
  &nbsp;&nbsp; Tested: $TESTED of $TOTAL
</div>
<div class="summary-bar" id="summary"></div>

<div class="retest-bar" id="retestBar">
  <span id="retestCount">0 selected</span> &mdash;
  <a href="#" id="downloadRetest">Download retest.txt</a>
  (save to <code>$OUT/retest.txt</code>, then run
   <code>./test_woz_batch.sh --out $OUT --retest $OUT/retest.txt</code>)
  &nbsp; | &nbsp; <a href="#" id="clearRetest">Clear</a>
</div>

<div class="filters">
  Filter:
  <button class="active" data-filter="all">All</button>
  <button data-filter="BOOTED">BOOTED</button>
  <button data-filter="TEXT_ONLY">TEXT_ONLY</button>
  <button data-filter="BLANK">BLANK</button>
  <button data-filter="TIMEOUT">TIMEOUT</button>
  <button data-filter="CRASH">CRASH</button>
</div>
<div id="lightbox"><img src="" alt=""></div>
<div id="report">
HTML_HEAD

# Group by (status, hash)
awk -F',' 'NR > 1 {
  key = $1 "|" $3
  count[key]++
  status[key] = $1
  size[key]   = $2
  hash[key]   = $3
  path = $6
  gsub(/^"/, "", path); gsub(/"$/, "", path)
  paths[key] = (paths[key] ? paths[key] SUBSEP path : path)
}
END {
  ord["BOOTED"]=0; ord["TEXT_ONLY"]=1; ord["BLANK"]=2
  ord["TIMEOUT"]=3; ord["CRASH"]=4
  n = 0
  for (k in count) keys[++n] = k
  for (i=1; i<=n; i++) for (j=i+1; j<=n; j++) {
    oi = ord[status[keys[i]]]; oj = ord[status[keys[j]]]
    if (oi > oj || (oi == oj && count[keys[i]] < count[keys[j]])) {
      t = keys[i]; keys[i] = keys[j]; keys[j] = t
    }
  }
  for (i=1; i<=n; i++) {
    k = keys[i]
    printf "<div class=\"group\" data-status=\"%s\">\n", status[k]
    printf "  <div class=\"group-header\">\n"
    if (hash[k] != "")
      printf "    <img src=\"shots/%s.png\" alt=\"\">\n", hash[k]
    else
      printf "    <div style=\"width:200px;height:96px;background:#333;color:#fff;display:flex;align-items:center;justify-content:center;font-family:monospace;\">no screenshot</div>\n"
    printf "    <div class=\"group-info\">\n"
    printf "      <span class=\"status %s\">%s</span>\n", status[k], status[k]
    printf "      <span class=\"count\">&nbsp; %d disk%s &nbsp; %d bytes &nbsp; hash %s</span>\n", \
           count[k], (count[k]==1?"":"s"), size[k], substr(hash[k], 1, 8)
    printf "    </div>\n"
    printf "    <label class=\"mark-group\"><input type=\"checkbox\" class=\"mark-group-cb\"> Mark all</label>\n"
    printf "  </div>\n"
    printf "  <details><summary>%d disk%s &mdash; click to expand</summary>\n", count[k], (count[k]==1?"":"s")
    printf "  <div class=\"disks\">\n"
    m = split(paths[k], arr, SUBSEP)
    for (j=1; j<=m; j++) {
      p = arr[j]
      # HTML-safe path for attribute and display
      pattr = p; gsub(/&/, "\\&amp;", pattr); gsub(/</, "\\&lt;", pattr)
      gsub(/>/, "\\&gt;", pattr); gsub(/\"/, "\\&quot;", pattr)
      printf "    <div><input type=\"checkbox\" class=\"retest-cb\" data-path=\"%s\"> %s <span class=\"cmd\">./obj_dir/Vemu --woz \"%s\"</span></div>\n", pattr, pattr, pattr
    }
    printf "  </div>\n"
    printf "  </details>\n"
    printf "</div>\n"
  }
}' "$CSV" >> "$HTML"

cat >> "$HTML" <<'HTML_FOOT'
</div>
<script>
  const groups = Array.from(document.querySelectorAll('.group'));
  const counts = {};
  let totalDisks = 0;
  groups.forEach(g => {
    const s = g.dataset.status;
    const m = g.querySelector('.count').textContent.match(/(\d+) disk/);
    const n = m ? parseInt(m[1]) : 0;
    counts[s] = (counts[s] || 0) + n;
    totalDisks += n;
  });
  const bar = document.getElementById('summary');
  ['BOOTED','TEXT_ONLY','BLANK','TIMEOUT','CRASH'].forEach(s => {
    if (counts[s]) {
      const pct = (100 * counts[s] / totalDisks).toFixed(1);
      bar.innerHTML += `<span><span class="status ${s}">${s}</span> ${counts[s]} (${pct}%)</span>`;
    }
  });

  // Filter
  document.querySelectorAll('.filters button').forEach(btn => {
    btn.addEventListener('click', () => {
      document.querySelectorAll('.filters button').forEach(b => b.classList.remove('active'));
      btn.classList.add('active');
      const f = btn.dataset.filter;
      groups.forEach(g => {
        g.style.display = (f === 'all' || g.dataset.status === f) ? '' : 'none';
      });
    });
  });

  // Retest selection tracking
  const retestBar = document.getElementById('retestBar');
  const retestCount = document.getElementById('retestCount');
  function updateRetestBar() {
    const sel = document.querySelectorAll('.retest-cb:checked');
    retestCount.textContent = `${sel.length} selected`;
    retestBar.classList.toggle('active', sel.length > 0);
  }
  document.addEventListener('change', (e) => {
    if (e.target.classList.contains('retest-cb')) updateRetestBar();
    if (e.target.classList.contains('mark-group-cb')) {
      const grp = e.target.closest('.group');
      // Expand details so changes are visible
      const d = grp.querySelector('details');
      if (d && e.target.checked) d.open = true;
      grp.querySelectorAll('.retest-cb').forEach(cb => cb.checked = e.target.checked);
      updateRetestBar();
    }
  });

  document.getElementById('downloadRetest').addEventListener('click', (e) => {
    e.preventDefault();
    const paths = Array.from(document.querySelectorAll('.retest-cb:checked'))
      .map(cb => cb.dataset.path);
    const blob = new Blob([paths.join('\n') + '\n'], {type: 'text/plain'});
    const a = document.createElement('a');
    a.href = URL.createObjectURL(blob);
    a.download = 'retest.txt';
    a.click();
  });
  document.getElementById('clearRetest').addEventListener('click', (e) => {
    e.preventDefault();
    document.querySelectorAll('.retest-cb:checked, .mark-group-cb:checked')
      .forEach(cb => cb.checked = false);
    updateRetestBar();
  });

  // Lightbox: click any thumbnail to show full-size; click overlay to close
  const lightbox = document.getElementById('lightbox');
  const lightboxImg = lightbox.querySelector('img');
  document.querySelectorAll('.group-header img').forEach(img => {
    img.addEventListener('click', () => {
      lightboxImg.src = img.src;
      lightbox.classList.add('open');
    });
  });
  lightbox.addEventListener('click', () => lightbox.classList.remove('open'));
  document.addEventListener('keydown', (e) => {
    if (e.key === 'Escape') lightbox.classList.remove('open');
  });
</script>
</body>
</html>
HTML_FOOT

echo ""
echo "==================== SUMMARY ===================="
awk -F',' 'NR > 1 {c[$1]++} END {for (s in c) printf "  %-10s %4d\n", s, c[s]}' "$CSV" | sort
echo ""
echo "Tested so far: $TESTED of $TOTAL"
echo "Unique screenshots: $(ls "$OUT/shots/" 2>/dev/null | wc -l | tr -d ' ')"
echo "Report: open $HTML"
